# Generated by Django 2.1.4 on 2018-12-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('unique_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('choice_description', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('function', models.TextField(blank=True)),
                ('condition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameStateChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=16)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='react_game_server.GameState')),
            ],
        ),
    ]
